tunnel: e3f59152-cb8a-43b0-adda-02f75aa8ec11
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: api.jonmaxjara.space
    service: http://api:3000
  - service: http_status:404

